import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const DICTIONARY = {
  en: {
    // Navigation & Common
    dashboard: 'Dashboard',
    overview: 'Your resource consumption overview',
    profile: 'Profile',
    settings: 'Settings',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    logout: 'Logout',
    createAccount: 'Create an account',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Keep me signed in',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    loading: 'Loading...',
    // Navigation labels
    aiInsights: 'AI Insights',
    reports: 'Reports',
    alerts: 'Alerts',
    leaderboard: 'Leaderboard',
    indiaMap: 'India Map',
    adminPanel: 'Admin Panel',
    administration: 'Administration',
    intelligence: 'Intelligence Platform',
    // Notifications
    notifications: 'Notifications',
    markAllRead: 'Mark All Read',
    viewAll: 'View all',
    refresh: 'Refresh',
    noNotifications: 'No new notifications. Great work staying ahead!',
    swipeToDismiss: 'Swipe to dismiss',
    latestAlerts: 'Latest alerts are shown here for quick review.',
    searchPlaceholder: 'Search anything...',
    // Profile
    fullName: 'Full Name',
    editProfile: 'Edit Profile',
    // AI Page
    aiAnalytics: 'AI & Smart Analytics',
    aiSubtitle: 'Intelligent insights, anomaly detection, forecasting, and personalized recommendations',
    forecastConfidence: 'Forecast confidence',
    anomalyAlerts: 'Anomaly alerts',
    savingsGuidance: 'Savings guidance',
    comingSoon: 'Coming Soon',
    
    // Dashboard Specific
    liveFeed: 'Live Feed',
    connected: 'Connected',
    disconnected: 'Disconnected',
    tariffEstimate: 'India Tariff Estimate',
    electricityUnits: 'Electricity Units (kWh)',
    waterLiters: 'Water Usage (L)',
    estimateBill: 'Estimated Bill',
    waterUsage: 'Water Usage',
    electricityUsage: 'Electricity Usage',
    totalCost: 'Total Cost',
    monthlySavings: 'Monthly Savings',
    simulateIoT: 'Simulate IoT',
    simulating: 'Simulating...',
    addReading: 'Add Reading',
    waterFlow: 'Water Flow',
    electricLoad: 'Electric Load',
    liveAlerts: 'Live Alerts',
    electricity: 'Electricity',
    water: 'Water',
    total: 'Total',
    recentAlerts: 'Recent Alerts',
    noRecentAlerts: 'No recent alerts',
    addMeterReading: 'Add Meter Reading',
    type: 'Type',
    value: 'Value',
    waterLitersLabel: '💧 Water (liters)',
    electricityKwhLabel: '⚡ Electricity (kWh)',
    usageTrends: 'Usage Trends',
    monthlyComparison: 'Monthly Comparison',
    costDistribution: 'Cost Distribution',
    
    // AI Insights
    anomalies: 'Anomalies',
    anomalyDetection: 'Anomaly Detection',
    noAnomalies: '✅ No anomalies detected. Usage patterns are normal!',
    forecast: 'Forecast',
    forecastTitle: '30-Day Forecast',
    predictions: 'Predictions',
    confidence: 'Confidence',
    recommendations: 'Recommendations',
    recommendationsTitle: 'Energy-Saving Recommendations',
    devices: 'Devices',
    deviceBreakdown: 'Device Breakdown',
    analytics: 'Analytics',
    analyticsTitle: 'Advanced Analytics',
    carbon: 'Carbon',
    carbonFootprint: 'Carbon Footprint',
    
    // Data fields
    totalUsage: 'Total Usage',
    dailyAverage: 'Daily Average',
    peakHours: 'Peak Hours',
    costPerUnit: 'Cost/Unit',
    estimatedBillAnalytics: 'Est. Bill',
    trend: 'Trend',
    carbonEmissions: 'Carbon Emissions',
    carbonSavings: 'Potential Savings',
    usageSpike: ' Usage Spike',
    usageDrop: ' Usage Drop',
    potentialSavings: 'Potential savings',
    priority: 'Priority',
    high: 'HIGH',
    medium: 'MEDIUM',
    low: 'LOW',
    
    // Units & Measurements
    units: 'Units',
    unitsPerDay: 'Units/day',
    tonnes: 'tonnes',
    liters: 'Liters',
    kwh: 'kWh',
    lpm: 'L/min',
    kw: 'kW',
    
    // Login & Auth
    welcomeToHydrogrid: 'Welcome to HydroGrid',
    intelligentCompanion: 'Your intelligent companion for water and electricity management. Track usage, save money, and reduce your environmental impact.',
    emailAddress: 'Email address',
    password: 'Password',
    enterCredentials: 'Enter your credentials to access your dashboard',
    dontHaveAccount: "Don't have an account?",
    createOne: 'Create one',
    haveAccount: 'Have an account?',
    quickDemoLogin: 'Quick Demo Login',
    
    // Landing Page
    startFreeTrial: 'Start Free Trial',
    viewDemoDashboard: 'View Demo Dashboard',
    freeToStart: 'Free to start',
    noCredit: 'No credit card',
    cancelAnytime: 'Cancel anytime',
    readyToGetStarted: 'Ready to Get Started?',
    joinThousands: 'Join thousands of users who are already saving money and reducing their environmental impact.',
    createFreeAccount: 'Create Free Account',
    
    // Profile & Settings
    manageAccount: 'Manage your account and preferences',
    badges: 'Badges',
    profileTab: 'Profile',
    settingsTab: 'Settings',
    timezone: 'Timezone',
    currency: 'Currency',
    locale: 'Locale',
    memberSince: 'Member Since',
    regionSettings: 'Regional Settings',
    utilityRates: 'Utility Rates',
    waterRate: 'Water Rate',
    electricityRate: 'Electricity Rate',
    
    // Feature Descriptions
    smartAlerts: 'Smart Alerts',
    securePlatform: 'Secure Platform',
    costSavings: 'Cost Savings',
    environmentalImpact: 'Environmental Impact',
    
    // Form Labels
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    age: 'Age',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    
    // Messages
    successMessage: 'Operation successful!',
    errorMessage: 'An error occurred',
    loadingMessage: 'Loading...',
    noData: 'No data available',
    connectionError: 'Connection error. Please try again.',

    // ── Alerts Page ──
    alertsSubtitle: 'Manage your threshold-based notifications',
    filterAll: 'All',
    filterUnread: 'Unread',
    filterCritical: '🔴 Critical',
    filterWarning: '🟡 Warning',
    filterInfo: '🟢 Info',
    noAlertsDisplay: 'No alerts to display',
    markAsRead: 'Mark as read',

    // ── Leaderboard Page ──
    efficiencyLeaderboard: 'Efficiency Leaderboard',
    leaderboardSubtitle: 'Most resource-efficient users ranked by cost per reading',
    refreshBtn: 'Refresh',
    fullRankings: 'Full Rankings',
    scoreLabel: 'Score',
    readingsLabel: 'readings',
    rupeePerReading: '₹/reading',

    // ── Reports Page ──
    reportsTitle: 'Reports & Analytics',
    reportsSubtitle: 'Generate detailed usage reports and cost analysis',
    generatingReport: 'Generating report...',
    startDate: 'Start Date',
    endDate: 'End Date',
    typeLabel: 'Type',
    allTypes: 'All',
    generateBtn: 'Generate',
    generatingBtn: 'Generating...',
    waterUsedLabel: 'Water Used',
    electricityUsedLabel: 'Electricity Used',
    waterCostLabel: 'Water Cost',
    totalCostLabel: 'Total Cost',
    avgPrefix: 'Avg',
    overDays: 'Over',
    days: 'days',
    dailyCostBreakdown: 'Daily Cost Breakdown',
    detailedData: 'Detailed Data',
    dateCol: 'Date',
    waterLCol: 'Water (L)',
    electricityKwhCol: 'Electricity (kWh)',
    waterCostCol: 'Water Cost',
    elecCostCol: 'Elec. Cost',
    totalCol: 'Total',

    // ── AI Insights Component ──
    aiForecastSnapshot: 'AI Forecast Snapshot',
    forecastTrendBadge: 'Forecast Trend',
    actualLabel: 'Actual',
    expectedLabel: 'Expected',
    deviationLabel: 'Deviation',
    avgWaterForecast: 'Avg water forecast',
    avgElecForecast: 'Avg electricity forecast',
    predictionTrend: 'Prediction trend',
    forecastNote: 'Dual-axis forecast showing water on the left and electricity on the right for cleaner trend comparison.',
    estimatedBillLabel: 'Estimated 30-day bill',
    noForecastData: 'No forecast data available',
    noDeviceData: 'No device data available',
    noCarbonData: 'No carbon data available',
    treesToPlant: 'Trees to Plant',
    toOffsetEmissions: 'To offset emissions',
    treesPerTonne: 'Trees per tonne',
    annualPotential: 'Annual potential',
    carbonTreeImpact: 'Environmental Impact',
    carbonOffsetMsg: 'To offset your current carbon emissions you need to plant trees.',
    carbonTrend: 'Carbon Trend (15 Days)',
    targetKg: 'Target (kg)',

    // ── AI Page info cards ──
    anomalyDetectionTitle: 'Anomaly Detection',
    anomalyDetectionDesc: 'Detects unusual usage patterns using statistical analysis. Get alerted to potential leaks or equipment failures before they become expensive problems.',
    forecastingTitle: 'Forecasting',
    forecastingDesc: 'Predicts your usage for the next 30 days using time-series analysis. Plan your budget and identify seasonal patterns accurately.',
    smartRecommTitle: 'Smart Recommendations',
    smartRecommDesc: 'Personalized suggestions to reduce consumption. Learn which appliances use the most energy and optimal times to use them.',
    comingSoonItems: [
      'Natural Language AI Chat - Ask questions naturally like "Why is my bill higher?"',
      'IoT Device Tagging - Automatically identify individual appliances',
      'Real-time Alerts - Instant notifications for anomalies',
      'Demand Response - Automatically optimize based on peak pricing',
    ],
  },
  hi: {
    // Navigation & Common
    dashboard: 'डैशबोर्ड',
    overview: 'आपकी संसाधन खपत का सारांश',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    signOut: 'साइन आउट करें',
    logout: 'लॉगआउट',
    createAccount: 'खाता बनाएं',
    forgotPassword: 'पासवर्ड भूल गए?',
    rememberMe: 'मुझे याद रखें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    submit: 'जमा करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    // Navigation labels
    aiInsights: 'AI अंतर्दृष्टि',
    reports: 'रिपोर्ट',
    alerts: 'सतर्कताएं',
    leaderboard: 'लीडरबोर्ड',
    adminPanel: 'एडमिन पैनल',
    administration: 'प्रशासन',
    intelligence: 'बुद्धिमान प्लेटफॉर्म',
    // Notifications
    notifications: 'सूचनाएं',
    markAllRead: 'सभी पढ़े हुए',
    viewAll: 'सभी देखें',
    refresh: 'रीफ्रेश',
    noNotifications: 'कोई नई सूचना नहीं। बहुत अच्छा!',
    swipeToDismiss: 'बंद करने के लिए स्वाइप करें',
    latestAlerts: 'नवीनतम सतर्कताएं यहाँ दिखाई जाती हैं।',
    searchPlaceholder: 'कुछ खोजें...',
    // Profile
    fullName: 'पूरा नाम',
    editProfile: 'प्रोफाइल संपादित करें',
    // AI Page
    aiAnalytics: 'AI और स्मार्ट विश्लेषण',
    aiSubtitle: 'बुद्धिमान अंतर्दृष्टि, विसंगति पहचान, पूर्वानुमान और व्यक्तिगत सिफारिशें',
    forecastConfidence: 'पूर्वानुमान विश्वास',
    anomalyAlerts: 'विसंगति सतर्कताएं',
    savingsGuidance: 'बचत मार्गदर्शन',
    comingSoon: 'जल्द आ रहा है',
    
    // Dashboard Specific
    liveFeed: 'लाइव फीड',
    connected: 'कनेक्टेड',
    disconnected: 'डिस्कनेक्टेड',
    tariffEstimate: 'भारत टैरिफ अनुमान',
    electricityUnits: 'बिजली यूनिट (kWh)',
    waterLiters: 'पानी उपयोग (L)',
    estimateBill: 'अनुमानित बिल',
    waterUsage: 'पानी उपयोग',
    electricityUsage: 'बिजली उपयोग',
    totalCost: 'कुल लागत',
    monthlySavings: 'मासिक बचत',
    simulateIoT: 'IoT सिमुलेट करें',
    simulating: 'सिमुलेट हो रहा है...',
    addReading: 'रीडिंग जोड़ें',
    waterFlow: 'पानी का प्रवाह',
    electricLoad: 'विद्युत भार',
    liveAlerts: 'लाइव सतर्कताएं',
    electricity: 'बिजली',
    water: 'पानी',
    total: 'कुल',
    recentAlerts: 'हाल के सतर्कताएं',
    noRecentAlerts: 'कोई हाल के सतर्कताएं नहीं',
    addMeterReading: 'मीटर रीडिंग जोड़ें',
    type: 'प्रकार',
    value: 'मूल्य',
    waterLitersLabel: '💧 पानी (लीटर)',
    electricityKwhLabel: '⚡ बिजली (kWh)',
    usageTrends: 'उपयोग प्रवृत्ति',
    monthlyComparison: 'मासिक तुलना',
    costDistribution: 'लागत वितरण',
    
    // AI Insights
    anomalies: 'विसंगतियां',
    anomalyDetection: 'विसंगति का पता लगाना',
    noAnomalies: '✅ कोई विसंगति नहीं पाई गई। उपयोग पैटर्न सामान्य है!',
    forecast: 'पूर्वानुमान',
    forecastTitle: '30 दिन का पूर्वानुमान',
    predictions: 'भविष्यवाणियां',
    confidence: 'आत्मविश्वास',
    recommendations: 'सिफारिशें',
    recommendationsTitle: 'ऊर्जा-बचत सिफारिशें',
    devices: 'डिवाइस',
    deviceBreakdown: 'डिवाइस विवरण',
    analytics: 'विश्लेषण',
    analyticsTitle: 'उन्नत विश्लेषण',
    carbon: 'कार्बन',
    carbonFootprint: 'कार्बन पदचिह्न',
    
    // Data fields
    totalUsage: 'कुल उपयोग',
    dailyAverage: 'दैनिक औसत',
    peakHours: 'पीक घंटे',
    costPerUnit: 'प्रति यूनिट लागत',
    estimatedBillAnalytics: 'अनुमानित बिल',
    trend: 'प्रवृत्ति',
    carbonEmissions: 'कार्बन उत्सर्जन',
    carbonSavings: 'संभावित बचत',
    usageSpike: ' उपयोग में वृद्धि',
    usageDrop: ' उपयोग में कमी',
    potentialSavings: 'संभावित बचत',
    priority: 'प्राथमिकता',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    
    // Units & Measurements
    units: 'यूनिट',
    unitsPerDay: 'यूनिट/दिन',
    tonnes: 'टन',
    liters: 'लीटर',
    kwh: 'kWh',
    lpm: 'L/मिनट',
    kw: 'kW',
    
    // Login & Auth
    welcomeToHydrogrid: 'HydroGrid में स्वागत है',
    intelligentCompanion: 'पानी और बिजली प्रबंधन के लिए आपका बुद्धिमान साथी। उपयोग ट्रैक करें, पैसा बचाएं, और अपने पर्यावरणीय प्रभाव को कम करें।',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    enterCredentials: 'आपके डैशबोर्ड तक पहुंचने के लिए अपने क्रेडेंशियल दर्ज करें',
    dontHaveAccount: 'खाता नहीं है?',
    createOne: 'एक बनाएं',
    haveAccount: 'खाता है?',
    quickDemoLogin: 'त्वरित डेमो लॉगिन',
    
    // Landing Page
    startFreeTrial: 'निःशुल्क ट्रायल शुरू करें',
    viewDemoDashboard: 'डेमो डैशबोर्ड देखें',
    freeToStart: 'शुरू करने के लिए निःशुल्क',
    noCredit: 'क्रेडिट कार्ड नहीं',
    cancelAnytime: 'कभी भी रद्द करें',
    readyToGetStarted: 'शुरू करने के लिए तैयार हैं?',
    joinThousands: 'हजारों उपयोगकर्ताओं में शामिल हों जो पहले से ही पैसा बचा रहे हैं और अपने पर्यावरणीय प्रभाव को कम कर रहे हैं।',
    createFreeAccount: 'निःशुल्क खाता बनाएं',
    
    // Profile & Settings
    manageAccount: 'अपने खाते और प्राथमिकताओं को प्रबंधित करें',
    badges: 'बैज',
    profileTab: 'प्रोफाइल',
    settingsTab: 'सेटिंग्स',
    timezone: 'समय क्षेत्र',
    currency: 'मुद्रा',
    locale: 'स्थान',
    memberSince: 'का सदस्य',
    regionSettings: 'क्षेत्रीय सेटिंग्स',
    utilityRates: 'उपयोगिता दरें',
    waterRate: 'पानी की दर',
    electricityRate: 'बिजली की दर',
    
    // Feature Descriptions
    smartAlerts: 'स्मार्ट सतर्कताएं',
    securePlatform: 'सुरक्षित मंच',
    costSavings: 'लागत बचत',
    environmentalImpact: 'पर्यावरणीय प्रभाव',
    
    // Form Labels
    name: 'नाम',
    email: 'ईमेल',
    phone: 'फोन',
    age: 'आयु',
    address: 'पता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिन कोड',
    
    // Messages
    successMessage: 'ऑपरेशन सफल!',
    errorMessage: 'एक त्रुटि हुई',
    loadingMessage: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    connectionError: 'कनेक्शन त्रुटि। कृपया फिर से प्रयास करें।',

    // ── Alerts Page ──
    alertsSubtitle: 'अपनी सीमा-आधारित सूचनाएं प्रबंधित करें',
    filterAll: 'सभी',
    filterUnread: 'अपठित',
    filterCritical: '🔴 गंभीर',
    filterWarning: '🟡 चेतावनी',
    filterInfo: '🟢 जानकारी',
    noAlertsDisplay: 'कोई सतर्कता नहीं',
    markAsRead: 'पढ़ा हुआ',

    // ── Leaderboard Page ──
    efficiencyLeaderboard: 'दक्षता लीडरबोर्ड',
    leaderboardSubtitle: 'प्रति रीडिंग लागत के आधार पर सबसे कुशल उपयोगकर्ता',
    refreshBtn: 'रीफ्रेश',
    fullRankings: 'पूर्ण रैंकिंग',
    scoreLabel: 'स्कोर',
    readingsLabel: 'रीडिंग',
    rupeePerReading: '₹/रीडिंग',

    // ── Reports Page ──
    reportsTitle: 'रिपोर्ट और विश्लेषण',
    reportsSubtitle: 'विस्तृत उपयोग रिपोर्ट और लागत विश्लेषण तैयार करें',
    generatingReport: 'रिपोर्ट तैयार हो रही है...',
    startDate: 'प्रारंभ तिथि',
    endDate: 'अंत तिथि',
    typeLabel: 'प्रकार',
    allTypes: 'सभी',
    generateBtn: 'तैयार करें',
    generatingBtn: 'तैयार हो रहा है...',
    waterUsedLabel: 'पानी उपयोग',
    electricityUsedLabel: 'बिजली उपयोग',
    waterCostLabel: 'पानी लागत',
    totalCostLabel: 'कुल लागत',
    avgPrefix: 'औसत',
    overDays: 'कुल',
    days: 'दिन',
    dailyCostBreakdown: 'दैनिक लागत विवरण',
    detailedData: 'विस्तृत डेटा',
    dateCol: 'तिथि',
    waterLCol: 'पानी (लीटर)',
    electricityKwhCol: 'बिजली (kWh)',
    waterCostCol: 'पानी लागत',
    elecCostCol: 'बिजली लागत',
    totalCol: 'कुल',

    // ── AI Insights Component ──
    aiForecastSnapshot: 'AI पूर्वानुमान सारांश',
    forecastTrendBadge: 'पूर्वानुमान प्रवृत्ति',
    actualLabel: 'वास्तविक',
    expectedLabel: 'अपेक्षित',
    deviationLabel: 'विचलन',
    avgWaterForecast: 'औसत जल पूर्वानुमान',
    avgElecForecast: 'औसत बिजली पूर्वानुमान',
    predictionTrend: 'भविष्यवाणी प्रवृत्ति',
    forecastNote: 'दोहरी-अक्ष पूर्वानुमान - बाईं ओर पानी, दाईं ओर बिजली।',
    estimatedBillLabel: 'अनुमानित 30-दिन का बिल',
    noForecastData: 'पूर्वानुमान डेटा उपलब्ध नहीं',
    noDeviceData: 'डिवाइस डेटा उपलब्ध नहीं',
    noCarbonData: 'कार्बन डेटा उपलब्ध नहीं',
    treesToPlant: 'पौधे लगाने हैं',
    toOffsetEmissions: 'उत्सर्जन ऑफसेट करने के लिए',
    treesPerTonne: 'प्रति टन पेड़',
    annualPotential: 'वार्षिक क्षमता',
    carbonTreeImpact: 'पर्यावरणीय प्रभाव',
    carbonOffsetMsg: 'अपने कार्बन उत्सर्जन को ऑफसेट करने के लिए पेड़ लगाएं।',
    carbonTrend: 'कार्बन प्रवृत्ति (15 दिन)',
    targetKg: 'लक्ष्य (kg)',

    // ── AI Page info cards ──
    anomalyDetectionTitle: 'विसंगति पहचान',
    anomalyDetectionDesc: 'सांख्यिकीय विश्लेषण से असामान्य उपयोग पैटर्न का पता लगाता है। संभावित लीक या उपकरण विफलताओं के बारे में पहले से सतर्क रहें।',
    forecastingTitle: 'पूर्वानुमान',
    forecastingDesc: 'समय-श्रृंखला विश्लेषण का उपयोग करके अगले 30 दिनों के उपयोग की भविष्यवाणी करता है। बजट की योजना बनाएं और मौसमी पैटर्न की पहचान करें।',
    smartRecommTitle: 'स्मार्ट सुझाव',
    smartRecommDesc: 'खपत कम करने के लिए व्यक्तिगत सुझाव। जानें कौन से उपकरण सबसे अधिक ऊर्जा उपयोग करते हैं।',
    comingSoonItems: [
      'प्राकृतिक भाषा AI चैट - स्वाभाविक रूप से प्रश्न पूछें जैसे "मेरा बिल अधिक क्यों है?"',
      'IoT डिवाइस टैगिंग - स्वचालित रूप से व्यक्तिगत उपकरण पहचानें',
      'रियल-टाइम सतर्कताएं - विसंगतियों के लिए तत्काल सूचनाएं',
      'डिमांड रिस्पांस - पीक मूल्य निर्धारण के आधार पर स्वचालित अनुकूलन',
    ],
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('hydrogrid_language') || 'en');

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const next = prev === 'en' ? 'hi' : 'en';
      localStorage.setItem('hydrogrid_language', next);
      return next;
    });
  };

  const value = useMemo(() => ({
    language,
    setLanguage,
    toggleLanguage,
    t: DICTIONARY[language] || DICTIONARY.en,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
